title: Zoe / 刘子玮 
# author: Author
email: zoeliuziwei@gmail.com
description: >- 
  Zoe's personal page
# baseurl: "/zoelzw" # the subpath of your site, e.g. /blog
google_analytics: 'UA-131540516-1' # change this to your GA key
url: "" # the base hostname & protocol for your site, e.g. http://example.com
include: ["_pages"] 
collections_dir: _collections
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# defaults:
#   - scope:
#       path: "assets/img"
#     values:
#       image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  projects:
    output: true
  research:
    output: true
  thoughts:
    output: true
